PARSER_BEGIN(Sintactico)
import java.util.*;
class Sintactico
{
    public static void main ( String[] args) throws ParseException
    {
        try
        {
            Sintactico a = new test (System.in) ; 
            a.Iniciar();
            System.out.println("La cadena fue aceptada correctamente");
        }
        catch(ParseException e)
        {
            System.out.println("Hubo un error ");
        }
    }

}
PARSER_END(test)

SKIP :
{
  " "
| "\r"
| "\t"
| "\n"
}

TOKEN :
