PARSER_BEGIN(test)
import java.util.*;
class test
{
    public static void main ( String[] args) throws ParseException
    {
        try
        {
            test a = new test (System.in) ; 
            a.Iniciar();
            System.out.println("La cadena fue aceptada correctamente");
        }
        catch(ParseException e)
        {
            System.out.println("Hubo un error ");
        }
    }
}
PARSER_END(test)

SKIP :
{
  " "
| "\r"
| "\t"
| "\n"
}

TOKEN :
{
    <#DIGITO:(["0"-"9"])+>
    | <#DECIMAL: <DIGITO>(".")?(<DIGITO>)?>
}

TOKEN:
{
    <TIPODATO: "int"|"decimal"|"string"|"hexdecimal"|"octal"|"bool"|"var">
    {System.out.println("Tipodato: "+image);}
    
    | <PUNTOYCOMA: ";">
    {System.out.println("Puntoycoma");}

    | <USANDO : "using" >
    {System.out.println("Usando");}

    | <NAMESPACE: "namespace">
    {System.out.println("Namespace");}

    | <IGUAL: "=">
    {System.out.println("Igual");}

    | <NUMERO:("+"|"-")?(<DECIMAL>)+>
    {System.out.println("NUMERO: "+image);}

    | <CLASE: "class">
    {System.out.println("Clase");}

    | <HTML_LETRA: "bold"|"italic"|"underscore"|"small"|"del"|"mark"|"strong"|"em"|"i"|"ins"|"sub"|"sup">
    {System.out.println("HTMLtipografia: "+image);}
        
    | <HTML_INTRO: "!DOCTYPE"|"html"|"head"|"title"|"body"|"h1"|"p">
    {System.out.println("HTMLintro: "+image);}
            
    | <HTML_STYLES: "style"|"background-color"|"color"|"font-family"|"font-size"|"text-align">
    {System.out.println("HTMLestilos: "+image);}
    
    | <HTML_QUOTCITA: "abbr"|"address"|"bdo"|"blockquote"|"cite"|"q">
    {System.out.println("HTMLcita: "+image);}
    
    | <HTML_RGB: "rgb">
    {System.out.println("HTML_rgb");}
    
    | <HTML_HSL: "hsl">
    {System.out.println("HTML_hsl");}
    
    | <HTML_IMAGE: "img"|"map"|"area"|"picture">
    {System.out.println("HTML_image: "+image);}
    
    | <HTML_TABLE: "table"|"th"|"tr"|"caption"|"colgroup"|"col"|"thead"|"tbody"|"tfoot">
    {System.out.println("HTML_table: "+image);}
    
    | <HTML_LINK: "href"|"target"|"mailto">
    {System.out.println("HTML_link: "+image);}
   
    | <HTML_LINK_ATTRIBUTE: "_self"|"_blank"|"_parent"|"_top">
    {System.out.println("HTML_atribute: "+image);}

    | <ORGANIZACION: "hotmail" | "gmail" >
    {System.out.println("Organizacion: "+image);}

    | <DOMINIO: "com" | "net" | "org" | "edu" | "gob" | "mil" | "es">
    {System.out.println("Dominio: "+image);}

    | <PROTOCOLO: "http" | "https" | "www" >
    {System.out.println("Protocolo: "+image);}

    | <OPLOGICO: "<=" | ">=" | "==" | "<" | ">"| "!=" >
    {System.out.println("Operador logico: "+image);}

    | <OPRELA: "&&" | "||" | "!" | "^^" | "~" >
    {System.out.println("Operador relacional: "+image);}

    | <ADICIONSUSTRACCION: "++" | "--" >
    {System.out.println("Adicion/sustraccion: "+image);}

    | <PREGUNTA: "if" >
    {System.out.println("Pregunta");}

    | <FIN_PREGUNTA: "endif " >
    {System.out.println("Fin_Pregunta");}

    | <CICLOS: "for" | "foreach" | "while">
    {System.out.println("Ciclos: "+image);}

    | <FIN_CICLOS: "endfor" | "endforeach" | "endwhile">
    {System.out.println("Fin ciclos: "+image);}

    | <IMPRIMIR: "cout"| "write" | "writeline">
    {System.out.println("Imprimir: "+image);}

    | <PILAS: "push" | "pop" | "peek">
    {System.out.println("Pilas: "+image);}

    | <COLAS: "lenght" | "tail" | "head" >
    {System.out.println("Colas: "+image);}

    | <HILO: "thread" | "threadstop">
    {System.out.println("Hilo: "+image);}

    | <OPERADORES: "+" | "-" | "*" | "/" >
    {System.out.println("Operadores: "+image);}

    | <TIPOMETODO: "public" | "private"  | "static" | "protected">
    {System.out.println("Tipometodo: "+image);}

    | <MODIFICADORES: "protected" >
    {System.out.println("Modificadores: "+image);}

    | <PROCEDIMIENTO: "void" >
    {System.out.println("Procedimiento");}

    | <TIPOGRAFICACION: "Mesh" | "Grid" | "MeshGrid"  >
    {System.out.println("Procedimientos: "+image);}

    | <COMENTARIO: "/*" | "*/" | "//" >
    {System.out.println("Comentario: "+image);}

    | <MAT_FUNCIONES: "abs" | "asin" | "asinh" | "acos" | "acosh" | "atan">
    {System.out.println("Funciones matematicas: "+image);}

    | <OBSOUND: "Sound" >
    {System.out.println("Obsound");}

    | <CONDITION: "true" | "false" | "null" | "nullptr" >
    {System.out.println("Condicion: "+image);}

    | <EXPREG: "regex" >
    {System.out.println("Expreg");}

    | <TYPEVARIBLE: "byte" | "char" | "decimal" | "float" | "int" | "double" | "long" | "sbyte" | "string" | "ulong" | "uint" | "intenger" | "bool" | "boolean" >
    {System.out.println("Tipo de variable: "+image);}

    | <COLECCIONES: "collections" >
    {System.out.println("Colecciones: "+image);}

    | <MATEMATICAS: "math" >
    {System.out.println("Matematicas");}

    | <RECORRIDA: "<<"|">>" >
    {System.out.println("Recorrida: "+image);}

    | <ALEATORIO: "random" | "rand" | "srand" >
    {System.out.println("Aleatorio: "+image);}

    | <CONSTANTES: "conts" | "constscast" | "constanst" >
    {System.out.println("Constantes: "+image);}

    | <INFO_OBJ: "sizeof" | "typeof" | "typedef" | "as" | "is" >
    {System.out.println("Información objeto: "+image);}

    | <ESTRUCTDATOS: "list" | "vector" | "register" | "stack" | "queue" >
    {System.out.println("Estructuras: "+image);}

    | <LLAVEIZQ: "{" >
    {System.out.println("llaveizq");}

    | <LLAVEDER: "}" >
    {System.out.println("llaveder");}

    | <PARENTESISIZQ: "(" >
    {System.out.println("parentesisizq ");}

    | <PARENTESISDER: ")" >
    {System.out.println("parentesisder ");}

    | <CORCHETEIZQ: "[" >
    {System.out.println("corcheteizq ");}

    | <CORCHETEDER : "]" >
    {System.out.println("corcheteder");}

    | <DEFINICIONSQL : "create" | "drop " | "alter" | "truncate">
    {System.out.println("DefinicionSQL: "+image);}

    | <MANIPULARSQL : "select" | "insert" | "update" | "delete" >
    {System.out.println("ManipularSQL: "+image);}

    | <CLAUSULASSQL : "from" | "group_by" | "having" | "order_by" | "where" >
    {System.out.println("ClausulasSQL: "+image);}

    | <AGREGADOSQL : "avg" | "count" | "sum" | "max" | "min" >
    {System.out.println("AgregadoSQL: "+image);}

    | <JUNTARSQL : "join" | "leftjoin" | "rightjoin"  >
    {System.out.println("JuntarSQL: "+image);}

    | <COMBINARSQL : "union" | "unionall" >
    {System.out.println("CombinarSQL: "+image);}

    | <VISITASSQL : "views" >
    {System.out.println("VistasSQL");}

    | <CREARARCHIVOS : "createFile" >
    {System.out.println("CrearArchivos");}

    | <ABRIRARCHIVOS : "openFile" | "openDiskFile" >
    {System.out.println("AbrirArchivos: "+image);}

    | <CERRARARCHIVOS : "closeFile" >
    {System.out.println("CerrarArchivos");}
    
    | <ELIMINARARCHIVOS : "deleteFile" >
    {System.out.println("EliminarArchivos");}    

    | <NOMBREARCHIVO : "fileName" >
    {System.out.println("NombreArchhivo");}

    | <MODOARCHIVO : "fileMode" >
    {System.out.println("ModoArhcivo");}

    | <IDENTIFICADOR : (["A"-"Z","a"-"z","0"-"9","_"])+>
}


void Iniciar() :
{
 ArrayList<String> TID = new ArrayList<String>();
 Token t;
 }
{
       (<TIPODATO> 
    |<PUNTOYCOMA>
    |<USANDO>
    |<NAMESPACE>
    |<IGUAL>
    |<NUMERO>
    |<CLASE>
    |<HTML_LETRA>
    |<HTML_INTRO>
    |<HTML_STYLES>
    |<HTML_QUOTCITA>
    |<HTML_RGB>
    |<HTML_HSL>
    |<HTML_IMAGE>
    |<HTML_TABLE>
    |<HTML_LINK>
    |<HTML_LINK_ATTRIBUTE>
    |<ORGANIZACION> 
    |<DOMINIO>
    |<PROTOCOLO>
    |<OPLOGICO>
    |<OPRELA>
    |<ADICIONSUSTRACCION>
    |<PREGUNTA>
    |<FIN_PREGUNTA>
    |<CICLOS>
    |<FIN_CICLOS>
    |<IMPRIMIR>
    |<PILAS>
    |<COLAS>
    |<HILO>
    |<OPERADORES>
    |<TIPOMETODO> 
    |<MODIFICADORES>
    |<PROCEDIMIENTO>
    |<TIPOGRAFICACION>
    |<COMENTARIO>
    |<MAT_FUNCIONES>
    |<OBSOUND>
    |<CONDITION>
    |<EXPREG>
    |<TYPEVARIBLE>
    |<COLECCIONES>
    |<MATEMATICAS>
    |<RECORRIDA>
    |<ALEATORIO>
    |<CONSTANTES>
    |<INFO_OBJ>
    |<ESTRUCTDATOS>
    |<LLAVEIZQ>
    |<LLAVEDER>
    |<PARENTESISIZQ>
    |<PARENTESISDER>
    |<CORCHETEIZQ>
    |<CORCHETEDER>
    |<DEFINICIONSQL>
    |<MANIPULARSQL>
    |<CLAUSULASSQL>
    |<AGREGADOSQL>
    |<JUNTARSQL>
    |<COMBINARSQL>
    |<VISITASSQL>
    |<CREARARCHIVOS>
    |<ABRIRARCHIVOS>
    |<CERRARARCHIVOS>
    |<ELIMINARARCHIVOS>
    |<NOMBREARCHIVO>
    |<MODOARCHIVO>
    |(t = <IDENTIFICADOR>
   {
int contador = 0;
String content = t.image;
while(contador<TID.size())
    {
        if(content.equals(TID.get(contador)))
            {
                break;
            }
        contador++;
    }
if(TID.size() == contador)
    {
        TID.add(content);
    }
System.out.println("Identificador: "+contador);

}))+<EOF>}
